name: tyme
description: A powerful Chinese calendar library supporting solar calendar, lunar calendar, 24 solar terms, constellations, zodiac signs, eight characters and more.
version: 1.3.8
homepage: https://github.com/6tail/tyme4dart

environment:
  sdk: ^3.5.4

dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

topics:
  - calendar
  - lunar
  - solar
  - chinese
  - almanac
